// users.js
import { faker } from '@faker-js/faker';

// Empty array to store users
const users = [];

/**
 * Function to add a new user with fake data generated by Faker
 */
export function addFakeUser() {
  const user = {
    name: faker.person.fullName(),
    street: faker.location.streetAddress(),
    country: faker.location.country(),
  };
  users.push(user);
  return user;
}

/**
 * Function to list all users
 */
export function listUsers() {
  return users;
}
